CREATE TABLE "HYEONJU"."ADMIN"
(	"ADMIN_NO" NUMBER,
"ADMIN_NAME" VARCHAR2(20 BYTE),
"ADMIN_ID" VARCHAR2(20 BYTE),
"ADMIN_DEPT" VARCHAR2(20 BYTE),
"ADMIN_RANK" VARCHAR2(20 BYTE),
"ADMIN_EMAIL" VARCHAR2(20 BYTE),
"ADMIN_BIRTH" DATE,
"ADMIN_TEL" VARCHAR2(20 BYTE),
CONSTRAINT "ADMIN_NO" PRIMARY KEY ("ADMIN_NO")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM"  ENABLE,
CONSTRAINT "ADMIN_ID" FOREIGN KEY ("ADMIN_ID")
REFERENCES "HYEONJU"."ACCOUNT" ("ID") ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;

CREATE TABLE "HYEONJU"."ACCOUNT"
(	"ID" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"ADMINISTRATOR" NUMBER(1,0) NOT NULL ENABLE,
CONSTRAINT "ID" PRIMARY KEY ("ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM"  ENABLE,
CONSTRAINT "ID_LENGTH" CHECK (LENGTH(ID) >= 5) ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;

CREATE TABLE "HYEONJU"."BANK"
(	"BANK_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"RATE" NUMBER DEFAULT 1.0 NOT NULL ENABLE,
CONSTRAINT "BANK_NAME" PRIMARY KEY ("BANK_NAME")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM"  ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;

CREATE TABLE "HYEONJU"."BANK_ACCOUNT"
(	"BA_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"BA_ID" VARCHAR2(20 BYTE),
"BA_PWD" VARCHAR2(20 BYTE),
"BA_BALANCE" VARCHAR2(20 BYTE),
"BA_RATE" VARCHAR2(20 BYTE),
"BA_STATUS" VARCHAR2(20 BYTE),
"BA_NAME" VARCHAR2(20 BYTE),
"BA_DATE" VARCHAR2(20 BYTE),
CONSTRAINT "BANK_ACCOUNT_PK" PRIMARY KEY ("BA_NUMBER")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM"  ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;

CREATE TABLE "HYEONJU"."DEAL"
(	"DEAL_NO" NUMBER NOT NULL ENABLE,
"DEAL_TYPE" VARCHAR2(20 BYTE),
"DEAL_DATE" VARCHAR2(20 BYTE),
"DEAL_HOST" VARCHAR2(20 BYTE),
"DEAL_HOSTBA" VARCHAR2(20 BYTE),
"DEAL_TARGETBANK" VARCHAR2(20 BYTE),
"DEAL_TARGETBA" VARCHAR2(20 BYTE),
"DEAL_BALANCE" VARCHAR2(20 BYTE),
"DEAL_TARGETSHOW" VARCHAR2(20 BYTE),
CONSTRAINT "TABLE1_PK" PRIMARY KEY ("DEAL_NO")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM"  ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;

CREATE TABLE "HYEONJU"."MEMBER"
(	"MEMBER_NO" NUMBER,
"MEMBER_NAME" VARCHAR2(20 BYTE),
"MEMBER_ID" VARCHAR2(20 BYTE),
"MEMBER_BIRTH" VARCHAR2(20 BYTE),
"MEMBER_EMAIL" VARCHAR2(20 BYTE),
"MERBER_TEL" VARCHAR2(20 BYTE),
"MEMBER_ADDR" VARCHAR2(20 BYTE),
"MEMBER_GENDER" VARCHAR2(20 BYTE),
"MEMBER_RANK" VARCHAR2(20 BYTE)
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;

CREATE TABLE "HYEONJU"."POST"
(	"POST_NO" NUMBER NOT NULL ENABLE,
"POST_TITLE" VARCHAR2(20 BYTE),
"POST_WIRTER" VARCHAR2(20 BYTE),
"POST_CONTENTS" NVARCHAR2(20),
"POST_BIRTH" VARCHAR2(20 BYTE),
CONSTRAINT "POST_PK" PRIMARY KEY ("POST_NO")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM"  ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;